extern const GeoLayout screen_001_switch_opt1[];
extern const GeoLayout screen_001_switch_opt2[];
extern const GeoLayout screen_001_switch_opt3[];
extern const GeoLayout screen_001_switch_opt4[];
extern const GeoLayout screen_001_switch_opt5[];
extern const GeoLayout screen_geo[];
extern u8 screen_tv_adjusted_ia8[];
extern u8 screen_whomp_ad_ci8[];
extern u8 screen_whomp_ad_pal_rgba16[];
extern u8 screen_wario_ad_ci8[];
extern u8 screen_wario_ad_pal_rgba16[];
extern u8 screen_hair_ad_ci8[];
extern u8 screen_hair_ad_pal_rgba16[];
extern u8 screen_late_ad_ci8[];
extern u8 screen_late_ad_pal_rgba16[];
extern u8 screen_pickle_ad_ci8[];
extern u8 screen_pickle_ad_pal_rgba16[];
extern Vtx screen_000_displaylist_001_mesh_layer_1_vtx_0[4];
extern Gfx screen_000_displaylist_001_mesh_layer_1_tri_0[];
extern Gfx mat_screen_blank[];
extern Gfx mat_revert_screen_blank[];
extern Gfx mat_screen_whomp_ad[];
extern Gfx mat_revert_screen_whomp_ad[];
extern Gfx mat_screen_wario_ad[];
extern Gfx mat_revert_screen_wario_ad[];
extern Gfx mat_screen_hair_ad[];
extern Gfx mat_revert_screen_hair_ad[];
extern Gfx mat_screen_late_ad[];
extern Gfx mat_revert_screen_late_ad[];
extern Gfx mat_screen_pickle_ad[];
extern Gfx mat_revert_screen_pickle_ad[];
extern Gfx screen_000_displaylist_001_mesh_layer_1[];
extern Gfx screen_000_displaylist_001_mesh_layer_1_mat_override_whomp_ad_0[];
extern Gfx screen_000_displaylist_001_mesh_layer_1_mat_override_wario_ad_1[];
extern Gfx screen_000_displaylist_001_mesh_layer_1_mat_override_hair_ad_2[];
extern Gfx screen_000_displaylist_001_mesh_layer_1_mat_override_late_ad_3[];
extern Gfx screen_000_displaylist_001_mesh_layer_1_mat_override_pickle_ad_4[];
